"""empty message

Revision ID: d3202da5e83b
Revises: 82d8ffbdde7f
Create Date: 2020-06-07 22:40:15.165316

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd3202da5e83b'
down_revision = '82d8ffbdde7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MovieCast')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MovieCast',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"MovieCast_id_seq"\'::regclass)'),
                              autoincrement=True, nullable=False),
                    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['actor_id'], ['Actor.id'], name='MovieCast_actor_id_fkey'),
                    sa.ForeignKeyConstraint(['movie_id'], ['Movie.id'], name='MovieCast_movie_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='MovieCast_pkey')
                    )
    # ### end Alembic commands ###
